"""
Day 19
• Docker	fundamentals
• Dockerfile	best	practice
• Multi-stage	builds

"""

"""
Docker: 
   - Docker is a tool that simplifies the process of developing, packaging, and deploying applications.
   - share the same os kernel 
   - works on rest api and follows the client-server architecture
        - docker cli
        - dockerd
        - docker engine

"""


"""
Dockerfile:
      - A Dockerfile is a text file that contains instructions for building a Docker image.
      - It defines the base image, the application code, dependencies, and any necessary configurations.
      - The Dockerfile is used by the Docker engine to create a containerized application.
   Best Practices:
      - Use a minimal base image to reduce the size of the final image.
      - Keep the Dockerfile simple and organized for better readability.
      - Use multi-stage builds to optimize the build process and reduce the final image size.
      - Avoid installing unnecessary packages or dependencies in the Docker image.
      - Use .dockerignore file to exclude files and directories that are not needed in the Docker image.
      - Do not give root access to the container, use a non-root user instead.
"""

"""
Multi-stage Builds:
   - Multi-stage builds allow you to use multiple FROM statements in a Dockerfile, which enables you to create intermediate images for building and testing your application, and then copy only the necessary artifacts to the final image.
   - This approach helps to reduce the size of the final image by excluding unnecessary build tools and dependencies.
   - The first stage is typically used for building the application, while the second stage is used for creating the final image that will be deployed.
"""


"""
Service Networking:
   - Docker provides a built-in networking system that allows containers to communicate with each other and with the host machine.
   - By default, Docker creates a bridge network for each container, which allows them to communicate with each other using their IP addresses.
   - You can also create custom networks to control how containers communicate with each other and with the host machine.
   - Docker supports different network drivers, such as bridge, host, overlay, and macvlan, which provide different levels of isolation and connectivity for containers.
   - bridge: default network driver, provides isolation between containers and the host machine.
   - host: allows containers to share the host machine's network stack, providing better performance but less isolation.
   - overlay: allows containers to communicate across multiple Docker hosts, providing a distributed network for containerized applications.
   - macvlan: allows containers to have their own MAC addresses and appear as physical devices on the network, providing better performance and isolation.
"""


"""
Caching: 
   - Docker uses a layer caching mechanism to optimize the build process and reduce the time it takes to build images.
   - Each instruction in a Dockerfile creates a new layer in the image, and Docker caches these layers to speed up subsequent builds.
   - If an instruction in the Dockerfile has not changed since the last build, Docker can reuse the cached layer instead of rebuilding it, which can significantly reduce build times.
   - To take advantage of caching, it's important to order the instructions in the Dockerfile in a way that minimizes changes to the earlier layers, as changes to later layers will invalidate the cache for all subsequent layers.
"""

"""
Volumes:
   - Docker volumes are a way to persist data generated by and used by Docker containers.
   - types of volumes:
      - Named volumes: These are managed by Docker and can be shared between multiple containers.
      - Bind mounts: These allow you to mount a directory from the host machine into a container, providing access to files and directories on the host.
      - tmpfs mounts: These are temporary file systems that are stored in memory and are not persisted to disk.
      
"""
